//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ToolId { get; set; }
        public int Assetnumber { get; set; }
        public string Description { get; set; }
        public int BrandId { get; set; }
        public string ActiveRetired { get; set; }
        public string CheckedOut { get; set; }
        public string Comment { get; set; }
        public string image { get; set; }
    }
}
