//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workspace
    {
        public int WorkspaceId { get; set; }
        public string Workspace1 { get; set; }
    }
}
